geometry:
  window:
    # width: 1280
    width: 2560
    # height: 720
    height: 1440
    xpos: 0
    ypos: 0
  control: 450
  plot: 350

glfwapp:
  rollout:
    count: 10
  plot:
    title: true
    x_min: -3.3
